---
abstract: A lightweight PSGI framework - Sessions in a Database
author:
  - 'Paul Lockaby <plockaby AT cpan DOT org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: prancer-session-store-database
no_index:
  directory:
    - t
    - inc
requires:
  Prancer: 1.00
  Plack: 0.9968
  Plack::Middleware::Session: 0.23
  DBI: 0
  Try::Tiny: 0
  perl: 5.010
version: 1.00
